EDITED HANSARD * NUMBER 91 
Thursday, April 23, 1998 
MULTILATERAL AGREEMENT ON INVESTMENT 
GOVERNMENT RESPONSE TO PETITIONS 
Introduction and first reading 
Multilateral Agreement on Investment 
Allotted Day-Hepatitis C 
Mr. Rey D. Pagtakhan 
Mr. Rey D. Pagtakhan 
Mr. Gurbax Singh Malhi 
Mr. Jake E. Hoeppner 
MINING HALL OF FAME 
Mr. Brent St. Denis 
BOOK AND READING SUMMIT 
Mrs. Madeleine Dalphond-Guiral 
Ms. Diane St-Jacques 
Mr. Robert D. Nault 
Mr. Robert D. Nault 
Hon. Harbance Singh Dhaliwal 
Hon. Arthur C. Eggleton 
Hon. Arthur C. Eggleton 
Ms. Diane St-Jacques 
Interparliamentary Associations-Speaker's Ruling 
BUSINESS OF THE HOUSE 
BUSINESS OF THE HOUSE 
Allotted Day-Hepatitis C 
(Division deemed requested and deferred) 
EDITED HANSARD * NUMBER 91 
Thursday, April 23, 1998 
The House met at 10 a.m. 
MULTILATERAL AGREEMENT ON INVESTMENT 
Hon. Sergio Marchi (Minister for International Trade, Lib.):
GOVERNMENT RESPONSE TO PETITIONS 
This is simply intended to protect consumers.  
MULTILATERAL AGREEMENT ON INVESTMENT 
Mr. Nelson Riis (Kamloops, NDP):
I could read a long list, but I will not.  
Mr. Nelson Riis (Kamloops, NDP):
Knowing what the provisions were for the last package they are totally panicked.  
Mr. Nelson Riis (Kamloops, NDP):
They are simply asking for comprehensive tax reform.  
Mr. Jim Gouk (West Kootenay-Okanagan, Ref.):
Mr. Paul Szabo (Mississauga South, Lib.):
Mr. Speaker, the following question will be answered today:
(b) The ROLF was implemented February 28, 1995. 
The revenue generated by the ROLF does not go directly toward the department's budget. 
The ROLF revenue assists to generally offset the costs throughout the immigration portfolio.  
(e) Please see response for (d) above.  
Mr. Speaker, I ask that all remaining questions be allowed to stand.  
Mr. John Cummins (Delta-South Richmond, Ref.):
I wonder if the member can tell me the status of those questions.  
Mr. Speaker, I have once again noted Questions Nos. 33, 51 and 56. 
Is it agreed that all the remaining questions shall stand?  
ALLOTTED DAY-HEPATITIS C 
Mr. Speaker, I rise on a point of order. 
They asked for a debate in the House. 
They asked the Prime Minister for that very thing. 
They sent him a letter saying ``Could we please debate this? 
The ALT test was by no means new. 
It was available and was accepted before. 
The date is an arbitrary legal date.  
There was no test available in 1989 for HIV. 
Has there been a floodgate of spurious medical claims because of that? 
Hepatitis C was as well.  
If I made a medical mistake, I would personally be sued for that mistake. 
I am thankful that never occurred over a 25 year span. 
This was for personal errors. 
If a manufacturer were to make faulty medical devices, it would be sued. 
The minister's argument is absolutely wrong.  
Let us go to the experience in other countries. 
I had a chance to talk with officials from Ireland. 
Their plan goes back to 1996 when they started paying individuals. 
That is an interesting thing which our government is trying to do. 
I do not understand this. 
Hepatitis C compensation would do exactly the same thing.  
Krever has said that the provinces as well as the federal government are responsible. 
The arguments fall completely apart. 
The regulators in Canada failed. 
A huge human tragedy resulted. 
Compensation should be paid to all those individuals.  
I have an escape for the government. 
I believe we should always try to provide an escape clause for the government. 
First it should be non-adversarial. 
That involves some scientific evidence. 
They should not be forced into taking a compensation package.  
Surely the Prime Minister as an experienced politician knows this. 
That is my plea. 
That is my wish. 
That is my hope. 
I challenge the Prime Minister to allow that to happen.  
Mr. Greg Thompson (Charlotte, PC):
We have to prove to Canadians that we are a compassionate country. 
Mr. Speaker, moral persuasion is sometimes a powerful persuasion. 
The persuasion I see as the most effective is the persuasion of the victims.  
I simply ask the victims who have suffered to go to their MPs. 
The victims will keep this debate alive. 
Those victims will not go away. 
The government does not have to lose face. 
Mr. Bill Blaikie (Winnipeg-Transcona, NDP):
I would like the hon. member's opinion on this. 
Let me read from the rules. 
They are not questions of confidence.  
The government will not fall on the basis of this. 
Mr. Randy White (Langley-Abbotsford, Ref.):
Mr. Speaker, it is a privilege to speak to this issue. 
I think such is the case for the federal government on this issue.  
That is when the Reform Party tabled a national victims bill of rights. 
Of course we all know what happened to that.  
We will develop a national victims bill of rights''. 
Today what do we have? 
Just a bunch of rhetoric. 
Is that familiar or what? 
It bent, took it into the House of Commons and said something would be done. 
The heat went off and it was dropped. 
This is exactly why.  
The minister's response was: 
I expect that other members of the government side will vote as they see fit.  
This is the identical issue. 
It is about rights. 
It is a supply day. 
It is an issue of confidence and therefore we must vote together on it. 
I just do not understand what is with this government. 
It does not make sense.  
I guess one of these days this will come back to haunt the government. 
The government cannot keep changing the rules as it sees fit.  
What kind of logic is there in this? 
These people are already victims. 
Many of them cannot afford the bills.  
Who gets something out of this? 
But what about the victims? 
It does not make sense. 
I would like to see members on the other side justify this in those terms. 
Let us talk about another issue. 
Of course it does. 
Does that make sense?  
Let us talk about something even closer to home for many of us. 
It calls this an issue of money. 
Let us look at some other things the government says it can afford. 
What kind of rationale could a government come up with to justify that?'' 
It is quite shameful actually.  
The government has compensated the east coast fishermen for the loss of their fishery. 
That the motion be amended by inserting after the word ``House'' the word ``strongly''.  
The amendment appears to be in order.  
Mr. Jim Gouk (West Kootenay-Okanagan, Ref.):
I also have another question if it is appropriate. 
Mr. Speaker, I will answer his second question first. 
It is ironic that all opposition parties raise this issue. 
The media looked at it. 
I think that is what he is in effect doing.  
Come on, Randy, tell us who it is.  
I know he would not want to do that. 
It would be a breach of the rules.  
The issue concerns everybody in opposition. 
It will just not go away. 
The other issue my colleague asked about was paying the bills for this. 
It will go on and on for years. 
It is a sad case for victims of hepatitis C. 
Mr. Peter Stoffer (Sackville-Eastern Shore, NDP):
However I have a slight concern. 
Would the hon. member comment on that?  
The NDP would be very wise to maybe expand its horizons. 
The House would be better off as well.  
Mr. Joseph Volpe (Parliamentary Secretary to Minister of Health, Lib.):
We should not exasperate that. 
In speaking about that progress, I will be speaking about partnership. 
A transition bureau has already been appointed. 
This is only right because the blood system belongs to each one of us.  
This is not just a technical or management exercise. 
They observed a fragmentation in blood science and research and development. 
Governments saw all this as well.  
What role does the federal government play in the new blood system? 
The role is quite different from that of the provinces and the territories. 
I think it is fair to say that the hon. member's time has expired. 
It is time for questions and comments.  
Mr. Grant Hill (Macleod, Ref.):
I would like to ask him a direct question.  
I will take the opportunity to do that now. 
Health Canada is a regulator of the blood supply system. 
Canadians deserve no less.  
Consumers sit on this council.  
The time for questions and comments has expired.  
Mrs. Pauline Picard (Drummond, BQ):
I did so with great compassion for the victims of this tragedy. 
Parliamentarians will recall that this inquiry ran into some roadblocks. 
Of this amount, the federal government's share will be $800 million. 
As my colleague has just said, these cuts could even be called extraordinary.  
It can and must set up a special no fault program. 
Mr. Mark Assad (Gatineau, Lib.):
Mr. Speaker, this issue has tragic implications. 
I think everyone in the House knows that.  
I was deeply touched by Mr. Saumure's testimony. 
Two of his brothers died of that terrible disease.  
If the provincial health ministers- 
Mr. Speaker, could I please continue?  
It was rather difficult to get the provinces to approve the agreement that was signed. 
This is a fundamental issue for everyone concerned.  
All this shouting is absolutely useless. 
We have a bunch of whiners on the other side, the NDP- 
The hon. member for Gatineau has the floor.  
So I am asking my colleague if she agrees.  
The time allotted for questions and comments has expired.  
Mr. Bill Blaikie (Winnipeg-Transcona, NDP):
One can imagine what that election might be like. 
It is not a hard and fast argument that the government is making. 
We are going to be saying this individually throughout the day.  
The only person making that ridiculous claim is the Prime Minister. 
In fairness, the Prime Minister is acting within the rules of the House. 
All these things are possible within the rules.  
The government is putting forward an argument that it is trying to be legally cautious. 
We have precedents already. 
Why not pay attention to that precedent? 
If we are precedent conscious, why not pay attention to that precedent? 
This morning we were at the prayer breakfast. 
Let us ask ourselves what would Jesus do in this situation. 
Mr. Werner Schmidt (Kelowna, Ref.):
Everyone makes a mistake once in a while. 
I wonder if the member would comment on that particular issue. 
What does generate confidence? 
I agree with the point the hon. member is making. 
I think there is a place for confidence. 
However, I believe that should be a limited range of proposals and things.  
Mr. Joseph Volpe (Parliamentary Secretary to Minister of Health, Lib.):
This is of course the place to have political discussions. 
Mr. Greg Thompson (Charlotte, PC):
That is absolutely ridiculous. 
What is the Prime Minister doing? 
Some of them have been brave enough to say that publicly.  
You are nodding in agreement. 
The government does not know how many there are. 
It could be 20,000, it could be 40,000, it could be more. 
But the victims of hepatitis C are innocent victims. 
They will have to go through the legal system to get compensation. 
That is their only recourse.  
It cannot sustain its position in the courts. 
It will lose its case in the courts. 
The government is going to put these people through a protracted court process. 
That is the sum of what we have been saying in the House.  
The minister is in a very tricky situation. 
Guess who he lost the fight to? 
The finance minister is the guy who is calling the shots.  
He is the guy who is calling the shots. 
He fudges on that answer. 
He does not say yes and he does not say no. 
That was just the legal fees. 
That did not purchase one helicopter. 
It does not end there. 
That cost the Canadian taxpayers another half a billion dollars.  
We have the Prime Minister sitting over there nodding in agreement with the health minister. 
What would have to happen?  
I said it was very simple. 
It is as easy as that.  
There is one person in this House who can change it. 
He can change it on a moment's notice. 
We know you are a student of history. 
Let us set the example and do it right here in this country.  
Mr. Speaker, thank you for your patience. 
I will entertain questions from other members. 
Mr. Joseph Volpe (Parliamentary Secretary to Minister of Health, Lib.):
The member probably will recall that all victims have recourse to the courts. 
There has to be approval by the courts if the package is accepted. 
That does not preclude any other packages that may be sought afterward. 
That does not exclude anyone. 
The rules of procedure allow everyone to seek satisfaction. 
The Government of Canada does not close the door on any of that.  
Mr. Speaker, on a point of order. 
Will the parliamentary secretary put his question? 
He has been going on long enough.  
The hon. member for Charlotte.  
Mr. Speaker, thank you for your wise intervention.  
We will support this motion because it is the right thing to do. 
We want all victims of hepatitis C compensated.  
Mr. Peter Stoffer (Sackville-Eastern Shore, NDP):
I would his comments and views on that appointment.  
Perhaps the hon. member could repeat his question more briefly. 
We have very limited time.  
I would like his comments on that appointment please.  
The human factor has to enter in here. 
Mr. Maurice Vellacott (Wanuskewin, Ref.):
I will read one in full and part of another. 
This letter was addressed to me: 
The date chosen, 1986, is entirely arbitrary. 
A very selective practice. 
The government is allowing the American practice in this case to dictate Canadian policy. 
There is no other good scientific reason for so doing. 
I urge him to refrain from doing so.  
That is reason enough to help them. 
These are people not only out of jobs but out of their lives. 
It has already taken three years. 
How many more years will victims have to wait? 
If he really wants to help taxpayers he will settle out of court. 
Each company owned up, faced responsibility and settled out of court. 
Why cannot the health minister do that?  
The Red Cross says half of that. 
What is the real number? 
The government should be giving compensation to all.  
Mr. Jim Hart (Okanagan-Coquihalla, Ref.):
I heard the parliamentary secretary speak about the future of the blood system. 
Those are all good things. 
His name is Chase Makarenko. 
Chase is an interesting young fellow. 
He required extensive chemotherapy and many medical procedures. 
Note the date, 1987.  
That leaves young Chase out of the compensation package. 
Now Chase has an uncertain future.  
Has the government considered that? 
I do not think so. 
If it has it has disregarded it. 
It wants to draw a line in the sand.  
I do not understand that. 
I would like the government to explain that to me. 
I met with the hepatitis C victims of Okanagan-Coquihalla last week. 
I have a lot of questions. 
I have a lot of heart wrenching stories. 
The Minister of Health does not want to meet with those victims. 
It is a sad day for Canadians.  
It was a tragic event and maybe they should receive compensation. 
I am not arguing that. 
Then she does the most amazing thing. 
Mr. Joseph Volpe (Parliamentary Secretary to Minister of Health, Lib.):
I think the debate would be helped along by recalling a couple of things. 
Madam Speaker, I rise on a point of order. 
It was a good presentation and one that deserves consideration by all members. 
I do not mean this to be trivial or partisan. 
It is an important thing to keep in mind.  
The point here is that the date does not matter. 
It is a legal argument.  
Young Chase was infected in 1987. 
Can he explain that to me?  
He said there was testing available in 1958. 
Why did the government not choose to take 1958 as the date? 
The fact is it is an arbitrary date.  
The member wants to ask me questions about a date I gave him. 
Mr. Maurice Vellacott (Wanuskewin, Ref.):
Madam Speaker, I touched on this point a little in my presentation. 
It is a terrible shame.  
I would hope to see the government move like the Irish government did. 
Now would be the time to do it because this government's decision is wrong. 
It is just wrong. 
The government should reflect on such people. 
Members of the Liberal Party should reflect on such people.  
Mr. Lynn Myers (Waterloo-Wellington, Lib.):
Justice Krever's final report is a comprehensive and exhaustive examination of the events. 
Any solutions must be governed by three principles. 
First, the safety of the blood supply must always come first. 
The key to success lies in the proper governance of the system. 
These are urgent matters and Health Canada fully recognizes that urgency. 
Mr. Darrel Stinson (Okanagan-Shuswap, Ref.):
Madam Speaker, I listened to the member's speech. 
He was talking about now and in the future. 
Madam Speaker, I thank the hon. member for his question.  
This is a decision fraught with a great deal of emotion. 
It is clear that it strikes at the heart of all Canadians. 
We very much appreciate that.  
Mr. Rey D. Pagtakhan (Parliamentary Secretary to Prime Minister, Lib.):
Madam Speaker, the motion before us states: 
I am inclined to support such a recommendation. 
That civil tort process is a lengthy one.  
We have not in this House held that debate.  
Where were they before? 
Did we hear from the opposition before on this issue?  
Consideration of ALT testing in Canada had not been ignored. 
By 1986, however, no such study had been undertaken''.  
I would like to get unanimous consent to continue.  
The Acting Speaker (Ms. Thibeault):
Is there unanimous consent?  
Mr. Grant Hill (Macleod, Ref.):
Madam Speaker, my colleague is a medical practitioner from days of old, as I am. 
That is a debatable question.  
Mr. Rey D. Pagtakhan:
Medical situations are complex and require a rational basis at all times. 
It is always a tenuous balance between risk and benefit. 
So I must say that the scientists of the day face a serious dilemma. 
Madam Speaker, I rise on a point of order. 
The hon. member from Reform asked him a pointed question. 
Mr. Rey D. Pagtakhan:
The question can be answered pointedly in the context of the greater whole. 
We cannot be simplistic in medicine. 
Life is not a simple entity.  
Mr. Jay Hill (Prince George-Peace River, Ref.):
I am afraid I cannot. 
In fact, it is a bloody disgrace what has happened in this country.  
Mr. Rey D. Pagtakhan:
Mr. Speaker, I rise on a point of order. 
I do not think that is a point of order. 
I think it is a matter of debate.  
This government damn well knows it.  
This letter was written on April 21 of this year. 
My life has not been the same since. 
It has been a constant strain on relationships with my family and friends. 
Her faith and prayers have been an inspiration to me. 
My brother died of cancer on October 26, 1997. 
I miss the close relationships I had with my sisters. 
I had no choice in this situation. 
I know my two constituency assistants in Fort St. John are watching this debate today. 
There is nothing that they nor I can do to really help these victims. 
Other than that there is precious little we can do to ease the suffering.  
It is up to the health minister and the Prime Minister. 
For God's sake vote for these victims.  
Mr. Greg Thompson (Charlotte, PC):
The point I want to make is simply this. 
I guess in the real world we would call that swallowing yourself whole. 
The parliamentary secretary swallowed himself whole on this one. 
Perhaps the member could comment on that.  
Mr. Rey D. Pagtakhan:
Mr. Speaker, I rise on a point of order. 
Mr. Speaker, unfortunately the hon. member is quite correct. 
I guess, to offset that, it brings out the best in some members.  
It has the opportunity to do what is right.  
Mr. Peter Stoffer (Sackville-Eastern Shore, NDP):
Mr. Speaker, I commend the hon. member for his wonderful speech.  
I am quoting directly: ``There are more important things here than money''. 
It is she who should get the credit, not myself.  
The member is quite right. 
It is worried about a precedent? 
Do what is right.  
Mr. Rey D. Pagtakhan (Parliamentary Secretary to Prime Minister, Lib.):
Mr. Speaker, I rise on a point of order. 
Does the House give its consent?  
I am sorry, there is no consent. 
That disposes of the point of order.  
Mr. Speaker, I rise on a point of order. 
Mr. Gary Lunn (Saanich-Gulf Islands, Ref.):
I have been following the debate in my office. 
We have heard a lot of heart wrenching testimonies. 
I am really frustrated at what this government is doing.  
Let me read from an article in the April 23 issue of the Toronto Star . 
What he is really doing here is bringing out a big hammer. 
This vote has been declared a whipped vote by the government. 
I got that from one of the Liberal members. 
I do not believe we will see any members on that side vote against. 
He is going to be in Cuba. 
I know the Prime Minister believes in democracy. 
He has expressed that to us and I believe that he does. 
To do this is absolutely dead wrong. 
They will have to look at themselves in the mirror, as will the Prime Minister.  
I do not know how much clearer we can get than that.  
I know an arbitrary date has been drawn in the sand. 
From everything that I have read, there was a test available. 
I will read parts of a letter. 
I will not read the entire letter because I do not have time. 
A constituent, Mrs. Betty Back of Victoria, wrote this letter to me. 
There is no cure. 
Transfusions were meant to save lives, not kill them, and kill it does. 
No one but no one should be discriminated against''. 
That is exactly what this government is doing. 
There will be no evidence to indicate when she got hepatitis C. 
Her point is exactly what we are debating. 
We cannot just draw a line in the sand. 
We know these tests were available. 
The evidence is out there. 
In my research I have seen different dates. 
All kinds of dates are thrown in here. 
They have been ordered. 
I see the smiles. 
The Prime Minister is concerned. 
He is treating this as a confidence vote.  
I am not suggesting this will bring down the government at all. 
It is never ever too late to right a wrong. 
I hope he does.  
I hope the Prime Minister is following this debate and listening to the arguments. 
If he is, I am sure he will have to do that. 
This government is losing that confidence. 
I ask the government to reconsider. 
Mr. Joseph Volpe (Parliamentary Secretary to Minister of Health, Lib.):
Mr. Speaker, I have a brief comment. 
I do not think that is very helpful to the debate.  
None of those avenues have been restricted or diminished. 
It is important to keep those things in mind to frame the debate.  
Mr. Speaker, I rise on a point of order. 
First of all, he said we are being coerced over here. 
I urge the hon. member to address his remarks to the Chair.  
Mr. Speaker, I apologize for that.  
That is the first point I make. 
In another one he has suggested that there is money in the system. 
What he is really suggesting is that we should download this on to the provinces. 
Again, this government does not want to face up to the responsibility.  
Why not compensate them?  
It has already been admitted that they were wrong. 
They have admitted that, but they want to go to the courts. 
They are the ones that should be advocating this.  
I cannot believe that a parliamentary secretary would suggest such a solution. 
Ms. Carolyn Parrish (Mississauga Centre, Lib.):
It is one more cruel irony in this tragic course of events.  
In 1977 I had a Caesarean section and a beautiful baby was delivered. 
I have lived until today to watch that daughter grow up. 
It requires a thorough and thoughtful debate. 
What can government do for innocent victims? 
Government can provide the best possible health care to Canadians. 
I have also spoken with the victims of this tragedy. 
I feel deep sympathy for them as individuals. 
I look forward to the vote on Tuesday. 
I have no difficulty supporting his decision.  
Mr. Grant Hill (Macleod, Ref.):
Therefore, I would like to pose a question to her. 
What does she have to say to that?  
Mr. Speaker, it is my pleasure to answer that question. 
When the party is in opposition it is very easy to criticize. 
It can just sit there and react.  
Mr. Peter Stoffer (Sackville-Eastern Shore, NDP):
I believe that the system in this country is there. 
Mr. Greg Thompson (Charlotte, PC):
How does the member square that with what the party wants to do? 
Have the Liberals not swallowed themselves whole on this issue of compensation?  
Mr. Speaker, that is a very interesting juxtaposition of ideas. 
I have to straighten out in my mind what he wants me to respond to. 
This Minister of Health has come up with government policy. 
I represent the Ontario caucus, which has 101 members. 
We all pretty well have faith in the decision. 
Mr. Jacques Saada (Brossard-La Prairie, Lib.):
Much thought had been put into it. 
There were indeed many aspects to take into consideration.  
But we are always seeking to know more.  
We have looked to other countries to see if we could learn anything from them. 
We did not learn much in the end.  
There would have been even more cases of infection. 
This is precisely what happened in Ireland.  
Care must, therefore, be taken when seeking examples to follow. 
The scientific community constantly distributes information on the international level.  
It is often said that social programs are not easily exported. 
This approach led us to concentrate on the period between 1986 and 1990.  
Mr. Maurice Godin (Chateauguay, BQ):
Mr. Speaker, I just to the member for Brossard-La Prairie. 
I cannot believe my ears. 
I hope he did not say what I think he did.  
Mr. Roy Bailey (Souris-Moose Mountain, Ref.):
Mr. Speaker, it has been a bad day. 
It is beautiful outside but not so great inside. 
I do not want to get down to anything but cold, hard facts. 
Let us look at reality.  
I wonder how the hon. member would respond to a cold, hard situation. 
They are not dealing with realities. 
They come in here with a canned speech and read it off. 
They stay to the party line. 
They are not thinking with their hearts. 
They do not have an answer to that question. 
Mr. Speaker, I think there are two issues to consider here. 
One has to do with the responsibility of the government- 
I would like to have a chance to answer. 
One has to do with a much broader issue, the no fault issue.  
The Krever report is simply saying, as it states on page 1044: 
Then a bit further on it states: 
Mr. Grant McNally (Dewdney-Alouette, Ref.):
Let us just do a quick summary of what we have heard so far today. 
This is a non-partisan issue. 
She concludes by saying please bring about just compensation. 
That is what I am compelled to do. 
It is so clear.  
There must be changes made to help compensate our ongoing burden of this illness. 
We are innocent victims of a crime that no one wishes to take responsibility of.  
I was running scared and the stress was unbelievable.  
I would appreciate hearing from you in the very near future. 
I have written to Mrs. Smith. 
I received another letter that was very disturbing to me. 
I know the individual who wrote to me. 
He was a community leader in the area in which I grew up. 
This is a wrong decision. 
Mr. Peter Stoffer (Sackville-Eastern Shore, NDP):
They think their lives are fine.  
Mr. John Nunziata (York South-Weston, Ind.):
I was a member of that party for a good number of years. 
It was a party that went to bat for innocent victims. 
It was a party that believed in fairness, equity and compassion.  
Now we have a Liberal government. 
The Ireland government has shown the way to compensate innocent victims. 
Mr. Speaker, I thank my hon. colleague for his comments and his question.  
I sincerely hope the government is able to do that.  
Mr. Gurbax Singh Malhi (Bramalea-Gore-Malton, Lib.):
Mr. Jake E. Hoeppner (Portage-Lisgar, Ref.):
Mrs. Judi Longfield (Whitby-Ajax, Lib.):
We will be marking Canada Book Day in my riding in a special way. 
Mr. Deepak Obhrai (Calgary East, Ref.):
We will no longer put up with their hatred. 
We will no longer put up with their violence.  
Ms. Eleni Bakopanos (Ahuntsic, Lib.):
Mr. Mauril Belanger (Ottawa-Vanier, Lib.):
Mr. Paul Steckle (Huron-Bruce, Lib.):
Mr. Eugene Bellemare (Carleton-Gloucester, Lib.):
Mr. Monte Solberg (Medicine Hat, Ref.):
It is ``zachor'' and it means to remember. 
Mr. Brent St. Denis (Algoma-Manitoulin, Lib.):
Ms. Raymonde Folco (Laval West, Lib.):
Ms. Diane St-Jacques (Shefford, PC):
Mrs. Christiane Gagnon (Quebec, BQ):
Mr. Denis Paradis (Brome-Missisquoi, Lib.):
Mr. Scott Brison (Kings-Hants, PC):
Hon. Herb Gray (Deputy Prime Minister, Lib.):
Hon. Herb Gray (Deputy Prime Minister, Lib.):
It is a matter of what a vote amounts to in a fundamental way. 
Miss Deborah Grey (Edmonton North, Ref.):
Hon. Herb Gray (Deputy Prime Minister, Lib.):
That is what is happening on every measure. 
Mr. Grant Hill (Macleod, Ref.):
Just what caused him to change his tune?  
Hon. Allan Rock (Minister of Health, Lib.):
Hon. Herb Gray (Windsor West, Lib.):
This is something the press should grasp. 
Mr. Gilles Duceppe (Laurier-Sainte-Marie, BQ):
Hon. Sheila Copps (Minister of Canadian Heritage, Lib.):
Mr. Gilles Duceppe (Laurier-Sainte-Marie, BQ):
Hon. Sheila Copps (Minister of Canadian Heritage, Lib.):
We know that a committee is looking at a rather important issue. 
Mrs. Suzanne Tremblay (Rimouski-Mitis, BQ):
Hon. Sheila Copps (Minister of Canadian Heritage, Lib.):
Hon. Allan Rock (Minister of Health, Lib.):
Hon. Herb Gray (Deputy Prime Minister, Lib.):
Mrs. Elsie Wayne (Saint John, PC):
Mr. Speaker, the health minister said yesterday that this was the age of class action. 
A lot of his caucus does not feel that way. 
Hon. Allan Rock (Minister of Health, Lib.):
The entire health care system always entails risks for every member of the public. 
Is the hon. member suggesting that all governments should compensate all victims all the time? 
Mr. Chuck Cadman (Surrey North, Ref.):
Hon. Anne McLellan (Minister of Justice and Attorney General of Canada, Lib.):
Mrs. Pauline Picard (Drummond, BQ):
Hon. Allan Rock (Minister of Health, Lib.):
Mr. Speaker, they have the money, they should pay. 
I personally was involved with Mr. Rochon in the discussions on this question. 
Why are Canadians still paying the highest personal income taxes in the G-7?  
Hon. Paul Martin (Minister of Finance, Lib.):
Hon. Paul Martin (Minister of Finance, Lib.):
Mr. Paul Crete (Kamouraska-Riviere-du-Loup-Temiscouata-Les Basques, BQ):
Mr. Paul Crete (Kamouraska-Riviere-du-Loup-Temiscouata-Les Basques, BQ):
Mr. Rahim Jaffer (Edmonton-Strathcona, Ref.):
Hon. Harbance Singh Dhaliwal (Minister of National Revenue, Lib.):
We are simplifying the administration. 
I am sure we have volunteers who can help them do that this year.  
Mr. Rahim Jaffer (Edmonton-Strathcona, Ref.):
When tough questions come up the Liberals will try anything to avoid answering them. 
Hon. Paul Martin (Minister of Finance, Lib.):
The hon. member for Argenteuil-Papineau.  
Mr. Maurice Dumas (Argenteuil-Papineau, BQ):
Mr. Speaker, my question is for the Minister of Foreign Affairs. 
The United States has continuously relied on Canada as an ally in international disputes. 
Hon. Lloyd Axworthy (Minister of Foreign Affairs, Lib.):
Mr. Art Hanger (Calgary Northeast, Ref.):
Hon. Arthur C. Eggleton (Minister of National Defence, Lib.):
That explains his memory loss.  
Mr. Art Hanger (Calgary Northeast, Ref.):
I think the minister should get a second opinion.  
Hon. Arthur C. Eggleton (Minister of National Defence, Lib.):
This matter has been properly looked into. 
Mr. Yvon Godin (Acadie-Bathurst, NDP):
Hon. David Anderson (Minister of Fisheries and Oceans, Lib.):
Mr. Speaker, the plan for gulf crabbers will soon be in place.  
Hon. David Anderson (Minister of Fisheries and Oceans, Lib.):
Hon. Allan Rock (Minister of Health, Lib.):
Hon. Herb Gray (Deputy Prime Minister, Lib.):
Mr. Benoit Serre (Timiskaming-Cochrane, Lib.):
Mr. Speaker, my question is for the Minister of Finance.  
Mr. Darrel Stinson (Okanagan-Shuswap, Ref.):
Hon. Sergio Marchi (Minister for International Trade, Lib.):
I am now ready to proceed with a ruling on this question of privilege.  
I regret having to make this statement so publicly. 
Mr. Randy White (Langley-Abbotsford, Ref.):
Mr. Speaker, I rise on a point of order. 
Have you referred the issue to the Board of Internal Economy? 
Do we table a motion in this House at this point in time?  
This motion has been referred to the Board of Internal economy.  
Mr. Chuck Strahl (Fraser Valley, Ref.):
Mr. Speaker, I rise on a point of order. 
I have only been here for four years. 
I have never seen this done. 
If it is being referred to the Board of Internal Economy, that is your decision. 
It is not a debatable motion. 
Mr. John Nunziata (York South-Weston, Ind.):
Mr. Speaker, I rise on a point of order. 
It is not a body that is open to members of parliament.  
That is the appropriate way. 
It is not the appropriate way to simply sweep this matter under the carpet.  
Colleagues, I thought that it was reasonably clear. 
I have ruled that it is not a prima facie case of contempt. 
That is the ruling I have made at this point. 
This point should sit where it is.  
Mr. Speaker, I rise on a point of order. 
Again, I have never seen this done. 
As far as I know this has never been done before. 
If something is wrong, we have always referred it to that committee. 
I have never seen this done before.  
For example independent members are not. 
I have never seen it done before.  
I have a point of privilege from the member for York South-Weston.  
Then you went on to say that it was not a breach of privilege. 
The hon. member does not have a point of privilege.  
Mr. John Solomon (Regina-Lumsden-Lake Centre, NDP):
Mr. Speaker, I rise on a point of order.  
With respect to establishing parliamentary associations, I am the whip for the NDP. 
The hon. member is correct.  
BUSINESS OF THE HOUSE 
Mr. Randy White (Langley-Abbotsford, Ref.):
Hon. Don Boudria (Leader of the Government in the House of Commons, Lib.):
If necessary the debate shall continue on Monday.  
This would take place and continue on next Thursday.  
Next Tuesday shall be an allotted day. 
In the evening we plan to hold a special take note debate on Bosnia.  
Mr. Greg Thompson (Charlotte, PC):
I hope you will give me a bit of time here. 
I do not know how we can fit this into a point of order. 
Mr. John Solomon (Regina-Lumsden-Lake Centre, NDP):
BUSINESS OF THE HOUSE 
Hon. Don Boudria (Leader of the Government in the House of Commons, Lib.):
The motion would be as follows: 
Mr. Speaker, I rise on a point of order. 
Who gives this guarantee?  
What we have is a miscommunication. 
I understood that I would only be sharing time with a Liberal member. 
I do not wish to share my time with a Liberal member. 
Mr. Speaker, if I may I will clear this matter up. 
I am the Liberal member who was designated to share time with the hon. member. 
I am quite prepared to give up my time.  
Is the matter settled?  
Members have heard the terms of the motion. 
We have already said no to that.  
That settles that little matter.  
ALLOTTED DAY-HEPATITIS C 
The House resumed consideration of the motion and of the amendment.  
Mr. Deepak Obhrai (Calgary East, Ref.):
The government has not made a hard decision. 
The government has made a cruel decision.  
This is justice denied for a group that is rapidly running out of time.  
We must act now because compensation and justice delayed are compensation and justice denied. 
I have some notes but I will not read them. 
I will speak based on what I feel. 
I sat here this morning listening to the government side. 
We are talking about people who were infected in the past. 
What is this nonsense? 
They are saying that there is compensation for some people and not for others. 
I am amazed to see government members skirting the issue. 
We now have one Liberal member giving his time to an independent member. 
That is all we are asking.  
It is the government's responsibility because this is a federally regulated institution.  
Maybe there are some politics behind this. 
An essential aspect of leadership is to acknowledge when you have made a wrong decision. 
This is the time to acknowledge it. 
Premier Klein did it. 
Premier Harris did it. 
This government can do it too. 
It is a matter of compassion.  
I appeal to government members, including backbenchers. 
Mr. John Bryden (Wentworth-Burlington, Lib.):
I would like to draw the hon. member's attention to an analogy.  
I draw the hon. member's attention to parallels like the Salk vaccine. 
It is exactly the same with insulin. 
Insulin was discovered by Sir Frederick Banting. 
Penicillin is a great example. 
The efficiency of antibiotics is deteriorating rapidly. 
Are we going to hold the government liable for a failure of medical technology?  
Mr. Speaker, after listening to the hon. member's question I feel sick.  
What has insulin to do with this?  
What has insulin to do with this? 
Did a federally-regulated body have tainted insulin given to people? 
Is that what he is saying?  
What we are saying here is very simple. 
Compensation has to be given to everybody who was infected. 
That is the question. 
Mr. John Nunziata (York South-Weston, Ind.):
Mr. Speaker, I appreciate the opportunity to speak to this matter. 
How is it that the Government of Canada can be so heartless and cruel? 
How is it that a Liberal government can take the position it is taking?  
I sat as a Liberal member of parliament for 12 years. 
I was a Liberal for many years before then. 
Pierre Trudeau would never have taken the position that this government has taken. 
Liberals have been calling me from across the country. 
Their families will suffer. 
Give them some dignity. 
Tell them the government cares. 
Tell them the government understands what they are going through.  
I do not believe this government understands the magnitude of the suffering. 
I know that many members across the way are deeply troubled by this.  
What a bogus position to take. 
What does that mean? 
They will be stripped of their responsibilities if they do not toe the party line.  
That is what is wrong with politics in Canada today. 
Are they representing themselves or are they representing their constituents?  
There will be a political price to pay. 
I can assure hon. members across the way of that. 
I say shame on him.  
But is it his decision? 
He is the guy that controls the purse strings. 
These are the people who support the Minister of Health. 
It is immoral, it is unjust and it is unfair. 
As I said, it is a betrayal.  
The Government of Canada, a previous government, appointed a royal commission of inquiry. 
The government's position challenges the integrity of the royal commission itself. 
He is saying that the position of the Government of Canada today cannot be justified.  
He looked into the eyes of suffering witnesses. 
That is what the government is doing. 
It is compensating some and not others. 
I expect the other members of the government side will vote as they see fit''.  
The position of the government today is morally wrong. 
Yesterday it announced record profits, the most in the history of the company. 
How can he hand over money?  
Did it contribute to the Liberal Party of Canada? 
We are dealing with people who will die. 
They are going to die. 
A constituent who lives in my riding has written to me. 
I will not quote from her letter. 
She is on Eileen Avenue in York South-Weston. 
They will go home and sleep well. 
Their children are healthy. 
Their spouses are healthy. 
What would Paul Martin, Sr. have done? 
He would have compensated all innocent victims of hepatitis C. 
All victims should be compensated.  
Mr. John Bryden (Wentworth-Burlington, Lib.):
I understand from the member that he was a Liberal for 14 years. 
Mr. Speaker, that is absolute pure nonsense. 
That member opposite lacks the spinal backbone to represent his constituents.  
I do not know if he knows his history. 
Mr. David Price (Compton-Stanstead, PC):
Mr. Speaker, very simply they should not even refer to the Prime Minister. 
The Prime Minister's office will be calling them. 
The whip will be calling them. 
When they have a difficult case the Prime Minister may be making those calls. 
I want to do what is right. 
Just ask the people of York South-Weston.  
Ms. Angela Vautour (Beausejour-Petitcodiac, NDP):
What is happening is totally disgusting. 
What we are seeing is a government that just does not care.  
I believe that in the Krever report it had been put on alert in 1981. 
Could the member confirm that for me?  
They are misstating fact.  
The fact is tests existed prior to 1986. 
There were opportunities available to Canada in order to prevent the tragedy that occurred.  
That is the model. 
That is the fair and compassionate way the government should follow.  
Mr. Dick Harris (Prince George-Bulkley Valley, Ref.):
Mr. Speaker, I am pleased to speak to this very tragic issue. 
That statement, that premise, is an absolute lie. 
The Liberal government knows it. 
They are having to live with it day after day.  
They are the most important part of this discussion.  
Why can the government not understand this? 
The government members do understand it. 
How can the government deny responsibility?  
This motion urges the government to respect the report of the Krever commission. 
That is a wonderful statement. 
At that time he was the assistant House leader.  
Mr. Joseph Volpe (Parliamentary Secretary to Minister of Health, Lib.):
Political tactics are fine. 
The Acting Speaker (Mr. McClelland):
The hon. member for Prince George-Bulkley Valley.  
Mr. Speaker, I cannot believe what I just heard. 
That is what happened.  
Mr. Rene Canuel (Matapedia-Matane, BQ):
A terrible injustice has been done. 
I call upon them to recognize that error. 
Mr. Speaker, the recommendations in the Krever commission are very clear. 
The government has displayed a reprehensible attitude on this issue. 
Mr. Derrek Konrad (Prince Albert, Ref.):
Mr. Speaker, it is really important to continue the debate on this issue. 
They are suffering a lot.  
They have not come to Ottawa for a holiday. 
There is no place to take a holiday right now. 
They are here because they are hurting.  
It is not our rhetoric that matters. 
It will not betray us for what we are. 
What betrays us is our actions. 
High flown words and intentions do not do anything. 
It is our actions that speak loudly.  
That gets them nothing. 
They cannot take that to the bank. 
They cannot live it in health. 
They cannot work because somebody felt sorry for them. 
They cannot put their children through university. 
What do they get from the Liberal government? 
What did they say? 
That way everybody would know. 
Everybody would be on the same line.  
They have alienated half the country. 
There is a constitutional challenge on it. 
The government forged ahead in the face of all that opposition. 
Now it is political consideration. 
That is what we want to see.  
No. They removed the insulation and compensated homeowners for what was happening.  
That is all we are asking. 
The government does not have to pay everybody for everything. 
We want to see some compassion. 
That does not hold water. 
I cannot understand where the Liberals are going. 
Ms. Angela Vautour (Beausejour-Petitcodiac, NDP):
Now today we see them calling for equity for everyone. 
That is something we often hear from the Reformers. 
The same thing goes for education.  
I wonder why they do not always support such ideas.  
Something of this nature is doing the right thing. 
Mr. John Bryden (Wentworth-Burlington, Lib.):
However it is controversial and there are feelings both ways. 
Even on our side there are some problems.  
I expect that members on the government side will vote as they see fit.  
Mr. Sarkis Assadourian (Brampton Centre, Lib.):
Can he confirm if that is the case?  
The Acting Speaker (Mr. McClelland):
Hon. Herb Gray (Deputy Prime Minister, Lib.):
What does this agreement say? 
We are dealing with an agreement made by all of them. 
They are steadfast in supporting this agreement.  
That is a strange comment coming from a Reform member. 
He said on April 7, according to the Toronto Star : 
This is a very complex issue. 
We have come up with an approach that is national in scope, fair and reasonable.  
There has been a very careful analysis and a decision was made. 
I support the decision that was made.  
That is not what the Reform Party or the other provincial parties are saying.  
The last speaker talked about how the Reform Party is a party of principle. 
They are not saying anything about the positions of those provincial governments.  
The Acting Speaker (Mr. McClelland):
The Acting Speaker (Mr. McClelland):
In that case the Deputy Prime Minister has a minute and a half left.  
Please give me a firm signal when that point is reached.  
Why do they not say what is wrong with this agreement?  
Why is the Parti Quebecois saying nothing?  
It shows that there is no real merit in their position.  
Members in the House should consider carefully their position on this serious matter. 
Mr. Grant Hill (Macleod, Ref.):
The very organization it was supposed to regulate.  
They joined in the agreement because obviously they felt they had some responsibility. 
Mr. Peter Stoffer (Sackville-Eastern Shore, NDP):
It is the federal government that should be showing leadership on this, not the provinces.  
In some cases there is overlap and they have to co-operate.  
That shows the lack of credibility in his position. 
We know that to be a fact.  
Mr. Derrek Konrad (Prince Albert, Ref.):
He said he urged the members of this House to vote against the motion. 
It is an interesting word he used. 
We believe in it and we stand by it.  
Hon. Allan Rock (Minister of Health, Lib.):
That is at the root of this difficult issue. 
This is not the first time we have had to confront that issue.  
What did they conclude? 
They concluded in their recommendations the following: 
That is exactly what the ministers of health have done in this instance.  
So when is it that no fault compensation should be offered? 
That is when the avoidable injuries occurred.  
What should governments do about people before 1986?. 
We must also do whatever we can to minimize risk in the future. 
That was on the agenda because of federal leadership. 
That is what happened here before January 1986.  
Where will it end? 
Mr. Grant Hill (Macleod, Ref.):
He said it plainer than I could ever say it. 
The federal government regulator failed the public.  
All I will say is that Krever is our expert. 
The health minister has turned down his expertise. 
If it is not true, take off the whip.  
Before January 1986 there was no fault on the part of government. 
The hon. member knows it.  
We do not accept that. 
Mr. Greg Thompson (Charlotte, PC):
Mr. Speaker, I support entirely what the member for Macleod said. 
He prefers to put the blame on someone else. 
It is as simple as that. 
He cannot dodge that bullet.  
The Acting Speaker (Mr. McClelland):
He will not confront the question. 
I put it simply. 
When should governments pay compensation? 
The member will not answer that question.  
The Prichard committee in 1980 was not a legal analysis. 
It was made up of health care experts who understood health policies. 
It leads to the conclusion that this motion is ill-founded and inappropriate. 
Mr. Peter Stoffer (Sackville-Eastern Shore, NDP):
I wish to refer to what we have heard in this House today. 
History will prove me right on that.  
He stands there and says they have emotional claims. 
The Acting Speaker (Mr. McClelland):
Mr. Speaker, I apologize. 
I will refrain from using such strong language.  
With that remark I will end my comments.  
Mr. Monte Solberg (Medicine Hat, Ref.):
They have followed it very closely and I think that Canadians are always compassionate.  
Let us go back through the chronology. 
They were all compensated. 
It is not only in Canada that this advice has been followed. 
The government has drawn an arbitrary line. 
It says January 1986 is the point at which it will start to pay compensation. 
It is that straightforward.  
The justice minister wants us to absolve the government of all blame. 
If it did not take those steps, then it is culpable. 
It is that straightforward.  
The second point I want to go to is the idea of a free vote. 
Let us let the people's representatives make that decision.  
We also know the government has spoken in the past. 
We view this issue as a moral issue. 
That is the true test. 
It being 5.15 p.m., it is my duty to interrupt the proceedings.  
Is it agreed that we call it 5:30 p.m.?  
Note the word clarification.  
The program has been anything but broad and inclusive.  
The Court Challenges Program is a notorious transgressor in this regard. 
It is a very clear conflict of interest. 
There is no logical reason for this inequality and discrimination against the group REAL Women. 
I enjoy thinking about this. 
So far so good.  
That is why the Court Challenges Program is such an absurd, offensive and unjust program. 
However that is the effect of the Court Challenges Program. 
By funding this biased organization, the government is meddling in the affairs of the judiciary. 
For all these reasons I brought this initiative forward. 
Let me read it into the record again: 
Is there unanimous consent to adopt and pass this motion?  
Mr. Chris Axworthy (Saskatoon-Rosetown-Biggar, NDP):
Is there something wrong with that? 
It is not whether it is true. 
I contend that most Canadians would disagree with that.  
Would there be many who would legitimately complain about that?  
We hear much from the Reform Party about families. 
Why would we not assist this mother to clarify this plainly unfair situation? 
We know for example that immigrant status is generally denied to persons with physical disabilities. 
I am sure we have all seen the unfairness of that system. 
Take the case of Mark Benner. 
He was born of a Canadian mother and an American father in the United States. 
Is there something justifiable about that discrimination? 
Ms. Paddy Torsney (Burlington, Lib.):
The issue we are debating is of great importance to Canada. 
It touches the heart of what defines our country. 
It deals with the core attributes of modern democratic societies. 
That country has modelled its own program after the Canadian program.  
The issue is the Court Challenges Program, which the opposition would like to kill. 
This program is a symbol of the Canadian commitment to democracy. 
It is also a tangible demonstration of our progressive Canadian identity.  
It provides a means for enforcing and clarifying the law. 
All Canadians and all citizens of the world can be proud of this accomplishment.  
Mr. Richard Marceau (Charlesbourg, BQ):
This motion reads as follows: 
The grounds for appeal against unjustified discrimination are not always easily determined. 
Once again, I would point out the implication of the recognition of language rights. 
Some will claim, and rightly so, moreover, that language rights are not sufficiently promoted. 
It is through language that people express themselves and make themselves understood. 
I urge my colleagues opposite to give this some thought.  
Mr. Peter MacKay (Pictou-Antigonish-Guysborough, PC):
I will speak to that later in my remarks. 
The program allows Canadians to clarify the Canadian charter rights that exist. 
We have seen in recent years Canada becoming an overlitigious society. 
Morals are sometimes shaped there. 
Ideological ideas are given a forum for discussion. 
Legal issues are explored in a more detailed fashion.  
We have become a more rights oriented society as a result of the charter. 
The court process of course can be very long and arduous. 
Calling for a blanket removal of this fund I suggest is not the answer. 
I would suggest that provincial bar societies might be canvassed. 
I suggest that this would in fact enhance the present program. 
Adapting the present program is a suggestion we put forward.  
This brings me to the closing point I would like to make. 
For the reasons I have set out, we cannot support this motion.  
Mr. Eric Lowther (Calgary Centre, Ref.):
I found a real inconsistency when we look at what is actually going on here.  
Why are those principles put in place? 
This is of particular concern to us with this program.  
Many of their interventions were funded by this program. 
That is what is happening to Canadian taxpayers thanks to this program.  
Those are all detailed in our policy. 
Mr. Maurice Vellacott (Wanuskewin, Ref.):
There are wealthy individuals. 
What we have here is a major problem. 
They already have this set idea of what is equality. 
The Court Challenges Program funds interest groups, not individuals. 
Also we mentioned before that there were groups. 
These other groups are cut off, shut out and not allowed in. 
The charter recognizes certain disadvantaged groups. 
If that were the case, both sides of the argument need to be heard. 
Both sides need to be heard in court. 
We go to court presuming that one side is right. 
It is doing an end run around the elected representatives of the people of Canada.  
That is their right. 
Is there unanimous consent that the motion be deemed adopted and passed?  
There is no unanimous consent.  
Mrs. Michelle Dockrill (Bras d'Or, NDP):
I hope that this new era will begin. 
We have a government body questioning and condemning the actions of the government. 
The orderly shutdown of Devco continues. 
The government continues to hide the truth. 
I hope you will indulge me one more time, Mr. Speaker. 
Mr. Gerry Byrne (Parliamentary Secretary to Minister of Natural Resources, Lib.):
Mr. Speaker, I would like to thank my hon. colleague for her intervention.  
But there is no such plan to terminate the operations of Devco. 
I am concerned with the hon. member's continual insistence that this strategy exists. 
Frankly, it does not exist. 
The allegation, being quite false, is not very helpful to the workers of Devco. 
The motion to adjourn the House is now deemed to have been adopted. 
(The House adjourned at 6.19 p.m.) 
